export default {
  'vue/attribute-hyphenation': 'error',
  'vue/attributes-order': 'error',
  'vue/comment-directive': 'error',
  'vue/component-definition-name-casing': 'error',
  'vue/component-tags-order': 'error',
  'vue/first-attribute-linebreak': 'error',
  'vue/html-closing-bracket-newline': 'error',
  'vue/html-closing-bracket-spacing': 'error',
  'vue/html-end-tags': 'error',
  'vue/html-indent': 'error',
  'vue/html-quotes': 'error',
  'vue/html-self-closing': 'error',
  'vue/jsx-uses-vars': 'error',
  'vue/max-attributes-per-line': 'error',
  'vue/max-len': [
    'error',
    {
      code: 80,
      ignoreComments: true,
      ignorePattern: 'd="([\\s\\S]*?)"',
      ignoreRegExpLiterals: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
      ignoreUrls: true,
      tabWidth: 2,
      template: 120,
    },
  ],
  'vue/multiline-html-element-content-newline': 'error',
  'vue/mustache-interpolation-spacing': 'error',
  'vue/no-lone-template': 'error',
  'vue/no-multi-spaces': 'error',
  'vue/no-multiple-slot-args': 'error',
  'vue/no-spaces-around-equal-signs-in-attribute': 'error',
  'vue/no-template-shadow': 'error',
  'vue/no-v-html': 'error',
  'vue/one-component-per-file': 'error',
  'vue/order-in-components': 'error',
  'vue/prop-name-casing': 'error',
  'vue/require-default-prop': 'error',
  'vue/require-explicit-emits': 'error',
  'vue/require-prop-types': 'error',
  'vue/singleline-html-element-content-newline': 'error',
  'vue/this-in-template': 'error',
  'vue/v-bind-style': 'error',
  'vue/v-on-event-hyphenation': [
    'error',
    'always',
    {
      autofix: true,
    },
  ],
  'vue/v-on-style': 'error',
  'vue/v-slot-style': 'error',
};
