export enum RouteName {
  Login = 'login',
  Settings = 'settings',
  Home = 'home',
  EventList = 'event-list',
  EventPage = 'event-page',
  Favorites = 'favorites',
  ProfilerCompare = 'profiler-compare',
  Metrics = 'metrics',
  NotFound = 'not-found',
  SentryExceptions = 'sentry-exceptions',
  SentryExceptionDetail = 'sentry-exception-detail',
  SentryTraces = 'sentry-traces',
  SentryTraceDetail = 'sentry-trace-detail',
  SentryLogs = 'sentry-logs',
}
