# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.4.x]

    steps:
    - uses: actions/checkout@v3
    - uses: c-hive/gha-yarn-cache@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install JS dependencies
      run: yarn install
    - name: Lint code style
      run: yarn lint
    - name: Run tests
      run: yarn test
    - name: Build dist files
      run: yarn generate
